LOCAL_PATH := device/lenovo/a328

TARGET_BOARD_PLATFORM := mt6582
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
ARCH_ARM_HAVE_VFP := true
TARGET_CPU_SMP := true
TARGET_ARCH := arm
ARCH_ARM_HAVE_NEON := true
TARGET_NO_BOOTLOADER := true
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_ARCH_VARIANT_CPU := cortex-a7
TARGET_CPU_VARIANT:= cortex-a7
TARGET_CPU_MEMCPY_OPT_DISABLE := true
BOARD_HAS_NO_SELECT_BUTTON := true
#TARGET_BUILD_VARIANT := eng

# kernel stuff
#TARGET_KERNEL_SOURCE := kernel/mediatek/kernel
#TARGET_KERNEL_CONFIG := a328_defconfig
#TARGET_KMODULES := true
TARGET_PREBUILT_KERNEL := device/lenovo/a328/kernel
BOARD_KERNEL_CMDLINE :=
#BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00008000 --ramdisk_offset 0x01000000 --tags_offset 0x00000100
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_CUSTOM_BOOTIMG_MK := device/lenovo/a328/Bootimg.mk
BOARD_MKBOOTIMG_ARGS := --board 1430311957

# Storage allocations
BOARD_BOOTIMAGE_PARTITION_SIZE := 10485760 #0x1000000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 10485760 #0x1000000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1551892480
BOARD_USERDATAIMAGE_PARTITION_SIZE := 2057306112
BOARD_FLASH_BLOCK_SIZE := 131072

# MTK Hardware
#BOARD_HAS_MTK_HARDWARE := true
#MTK_HARDWARE := true
#COMMON_GLOBAL_CFLAGS += -DMTK_HARDWARE
#COMMON_GLOBAL_CPPFLAGS += -DMTK_HARDWARE

BOARD_GPS_LIBRARIES := true

TARGET_POWERHAL_VARIANT := cm

# Bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_MTK := true
BOARD_BLUETOOTH_DOES_NOT_USE_RFKILL := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/lenovo/a328/bluetooth

#Camera
USE_CAMERA_STUB := true

#BOARD_USES_GENERIC_AUDIO := true

# Recovery
TARGET_RECOVERY_FSTAB := device/lenovo/a328/rootdir/root/recovery.fstab

BOARD_RECOVERY_SWIPE := true

# TWRP stuff
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TW_EXTERNAL_STORAGE_PATH := "/sdcard"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "sdcard"
TW_DEFAULT_EXTERNAL_STORAGE := true
TW_INCLUDE_JB_CRYPTO := true
TW_CRYPTO_FS_TYPE := "ext4"
TW_CRYPTO_REAL_BLKDEV := "/dev/block/mmcblk0p7"
TW_CRYPTO_MNT_POINT := "/data"
TW_CRYPTO_FS_OPTIONS := "nosuid,nodev,noatime,discard,noauto_da_alloc,data=ordered"
TW_BRIGHTNESS_PATH := /sys/class/leds/lcd-backlight/brightness
TW_MAX_BRIGHTNESS := 255
TW_NO_USB_STORAGE := true

# OpenGL
USE_OPENGL_RENDERER := true
BOARD_EGL_CFG := device/lenovo/a328/configs/egl.cfg

BOARD_CONNECTIVITY_VENDOR := MediaTek
BOARD_CONNECTIVITY_MODULE := conn_soc
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_mt66xx
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_mt66xx
WIFI_DRIVER_FW_PATH_PARAM:="/dev/wmtWifi"
WIFI_DRIVER_FW_PATH_STA:=STA
WIFI_DRIVER_FW_PATH_AP:=AP
WIFI_DRIVER_FW_PATH_P2P:=P2P
#HAVE_CUSTOM_WIFI_DRIVER_2 := true
#HAVE_INTERNAL_WPA_SUPPLICANT_CONF := true
#HAVE_CUSTOM_WIFI_HAL := mediatek

MALLOC_IMPL := dlmalloc
DEVICE_RESOLUTION := 480x854

BOARD_RIL_CLASS := ../../../device/lenovo/a328/ril/

TARGET_GLOBAL_CFLAGS   += -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := false

# SELinux
BOARD_SEPOLICY_DIRS += \
    device/lenovo/a328/sepolicy

BOARD_SEPOLICY_UNION += \
    file_contexts \
    device.te \
    app.te \
    netd.te

#WITH_DEXPREOPT := false

TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/devices/platform/mt_usb/musb-hdrc.0/gadget/lun%d/file"
BOARD_VOLD_EMMC_SHARES_DEV_MAJOR := true

# By MediaTek
BOARD_USES_6575_HW := true
BOARD_USES_MTK_JPEG_HW_DECODER := true
BOARD_USES_YUSU_LCD_HW_OVERLAY := true
BOARD_USES_ARGB8888_FB := true
BOARD_ENABLE_MFG_HARDWARE := true
MFG_HALCOMPOSITION_BYPASS := false
MFG_ENABLE_GRALLOC_PMEM := true
BOARD_USES_YUSU_MP3_PROPRIETARY_CODEC := true
USES_MTK_OMX_CORE := true
BOARD_USES_ANDROID_DEFAULT_CODE := false
BOARD_USES_6575_MFV_HW := true
BOARD_USES_MTK_VPX_DEC := true
USES_CACHE_PMEM := true
